# Generated by Django 5.0.2 on 2025-04-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_otpverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
